#!/bin/bash

mkdir -p /tmp/rom # Where to sync source
cd /tmp/rom
. /tmp/ci/function

SECONDS=0

if [[ $git_cookies != 0 ]]; then

sudo touch /etc/mtab
sudo chmod 777 /etc/mtab

echo "$git_cookies" > ~/git_cookies.sh
bash ~/git_cookies.sh

fi

# Sync source
repo init -u https://github.com/ForkLineageOS/android.git -b lineage-19.1 -g default,-mips,-darwin,-notdefault

# Sync source without unnecessary messages, try with -j30 first, if fails, it will try again
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j$(nproc --all) || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j$(nproc --all)

## local manifest
git clone https://github.com/pjgowtham/android_device_oplus_RMX3360 -b lineage-19.1 device/oplus/RMX3360
git clone https://github.com/pjgowtham/android_device_oplus_sm8350-common -b lineage-19.1 device/oplus/sm8350-common
git clone https://gitlab.com/S8M1T/proprietary_vendor_oplus -b lineage-19.1 vendor/oplus
git clone https://github.com/pjgowtham/android_kernel_oplus_sm8350 -b lineage-19.1-RMX3360-S-source kernel/oplus/sm8350
git clone https://github.com/pjgowtham/android_hardware_oplus -b lineage-19.1 hardware/oplus

tg "$rom_name source sync completed!
Total Size: $(du -sh /tmp/rom | cut -d - -f 1 | cut -d / -f 1)
Time Took: $(($SECONDS / 60)) minute(s) and $(($SECONDS % 60)) second(s).
Status: $progress"

echo "$(($SECONDS / 60))" > /tmp/sync_time.txt
